main: main.o fibonacciRecursivo.o ordenacionSeleccion.o multiplicarMatrices.o sistemaEcuaciones.o clean
	g++ main.cpp ordenacionSeleccion.cpp multiplicarMatrices.cpp fibonacciRecursivo.cpp funciones.cpp sistemaEcuaciones.cpp

clean:
	rm *.o
